apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-cd-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ci-cd-demo
  template:
    metadata:
      labels:
        app: ci-cd-demo
    spec:
      containers:
        - name: ci-cd-demo
          image: <DOCKER_USERNAME>/ci-cd-demo:latest
          ports:
            - containerPort: 3000
